Python3 compatibility
ooz/epages-rest-python pull request #2
Opened 2018-01-05 13:57 UTC by tswfi

on top of #1 fixes the current test suite to run on python3. No other checks have been made.

2018-01-05 14:14 UTC, ooz requested changes

2018-01-05 14:14 UTC, ooz commented on epages/auth.py
> +    message = b'%s:%s' % (code, access_token_url)
I'd rather pass (unicode) strings as parameters and encode to bytestrings in the function to have an easier-to-use interface

2018-01-05 14:14 UTC, ooz commented on tests/test_auth.py
> +SIGNATURE = b'g1L73Mv6GnUE8vfWHmxKQmG9KuLiwwI9LMR50w+SXTo='
See comment above, please value the method contract and encode strings to bytestrings in the method

2018-01-05 21:53 UTC, tswfi commented
Like that? I don't usually use 2 so I'm not that familiar on how the string handling works there :)

2018-01-10 09:19 UTC, ooz commented
Looks good to me.

Problem now though: If I merge this it breaks Python 2 compatibility, because
```
except epages.RESTError as error:
```
is Python 3 only.

A solution to this would probably be some compatibility library (2to3, six?)

2018-01-10 10:24 UTC, ooz commented
You are correct!

Wierd, I'm certain, I tried this some time ago and it did not work.

2018-01-10 10:24 UTC, ooz approved these changes

2018-01-10 10:25 UTC, merged